### ISSUE TITLE
Releasing the next version - TODO

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#64]
Hi team (@nicbell & @ashleynolan), there are still a few things to do for the next version before it can be released.

- [x] Complete all tasks in #60 
- [x] Port all changes to the generator, see https://github.com/TryKickoff/generator-kickoff/issues/10 for what's needed
- [x] Update any documentation on the trykickoff.com site.
 - I have made many improvements but I will need some help with the homepage content. Have a look, you will see that I have added a feature overview section that needs completing.
- [x] Update [the changelog](https://github.com/TryKickoff/kickoff/blob/next/changelog.md) with any changes (this is nearly completed)
- [ ] Write a blog post about the release

Is there anything else?

**Comment by ashleynolan** [comment]
Doesn’t need to happen pre release, but I’ll need to update Statix with v6 once it’s finalised.  Just putting this in here as a note to myself to do so :shipit:

**Comment by nicbell** [comment]
Do you need me to update block grids docs on trykickoff.com?

**Comment by mrmartineau** [comment]
@nicbell I think I've done it, but it should all be double-checked.
