### ISSUE TITLE
Version 7 - TODO

### ISSUE THREAD

**Issue by mrmartineau** [TryKickoff/kickoff#72]
- [x] ES2015 by default using babel - most of this work has already been done in the [ES2015 branch](https://github.com/TryKickoff/kickoff/tree/es2015)
- [x] Eslint - switch to use eslint instead of jscs and jshint - most of this work has already been done in the [ES2015 branch](https://github.com/TryKickoff/kickoff/tree/es2015)
- [x] Flexbox - provide a good, flexbox-based alternative to the kickoff grid and block-grids. My recommendation is to use [suitcss/components-grid](https://github.com/suitcss/components-grid/) (I think this may need to be ported to Sass for ease of use..). Would be nice to install CSS dependencies with npm though..
- [x] Remove Grunticon - I think there are better icon solutions out there. Perhaps we don't need to include one at all. Controversial??
- [x] Drop IE8 support. I think its time now. We can remove the 2 CSS file generation, the question in the Yeoman generator and various other things..
- [x] Other CSS improvements. I have a list of various things I'd like to do after having read @leaverou's CSS book recently

What do you think @nicbell, @ashleynolan & @munkychop? Did I miss anything? Should we remove any files, rearrange any directories? I would like Kickoff to be as useful as possible.

**Comment by ashleynolan** [comment]
I’m down with all of it – only thing I’d probably change is to drop IE8 support in Kickoff, but keep it in the generator as an option possibly?

In regard to the block grids, I’ve updated them on a current project to use Flexbox, which is pretty straightforward to do – I can make a branch for this to see what you think (I can do this next week, as I’m putting some time aside in work to do Statix and Kickoff stuff in the next couple of weeks).  If we want to move completely away from the current grid (is there a need to do this?), I think we should probably take a look at a few other options as well and see which ones we prefer.

Rest of the list looks good though – sorry I’ve been a bit unreliable the last few weeks.  Been meaning to take a look at a few things but wedding planning took over temporarily after the engagement!

**Comment by mrmartineau** [comment]
Have a look at https://github.com/suitcss/components-grid/, it actually has many features that covers both block-grids and the standard grid, and then some.

As for dropping IE8, I think its time now. We could keep it in the generator as we currently do, but I'd even argue to get rid of it entirely. As a fallback, we could provide instructions on the trykickoff.com site to  show how support could be added.

**Comment by mrmartineau** [comment]
SuitCSS also have [suitcss/utils-flex](https://github.com/suitcss/utils-flex) which might be useful..test page can be found here: http://suitcss.github.io/utils-flex/test/

**Comment by mrmartineau** [comment]
@ashleynolan & @nicbell I have created some branches for [flexbox](https://github.com/TryKickoff/kickoff/tree/flexbox-grid) ([see commits](https://github.com/TryKickoff/kickoff/commits/flexbox-grid)) and the removal of [old IE](https://github.com/TryKickoff/kickoff/tree/flexbox-grid) ([see commits](https://github.com/TryKickoff/kickoff/commit/e70ab083fb902897c773b0b85053e19664f454b0)). Please review them both and, in particular, the flexbox stuff. There's a demo you can try if you checkout the code :wink:

I also, creates the [ES2015 branch](https://github.com/TryKickoff/kickoff/tree/es2015) ([see commits](https://github.com/TryKickoff/kickoff/commits/es2015)). I'm fairly certain that everything is fine with it but it would be good to get a 2nd/3rd pair of eyes on it.

Cheers guys

**Comment by mrmartineau** [comment]
Regarding the removal or replacement of Grunticon: I have been using SVG sprites a lot recently and feel that they are a perfect replacement.. Find out more at https://css-tricks.com/svg-sprites-use-better-icon-fonts/ and you can see them in use on [my site](http://martineau.tv).

Two grunt plugins for generating SVG sprites from a folder full of SVGs are:
* https://www.npmjs.com/package/grunt-svgstore
* https://www.npmjs.com/package/grunt-svg-symbols

Let me know what you think.

**Comment by ashleynolan** [comment]
Re an image solution to replace Grunticon – I would lean towards not including an image solution at all (except tasks for minifying images and SVGs perhaps).

I think every project is completely different and every dev approaches images in very different ways, so as long as we make it easy for people to add a solution in (and make that clear), that’s the most important thing.  I think this is especially true at the moment with HTTP2 just around the corner (or here right now for most people), which will make spriting and using data-uri’s much less important.

Thoughts?

**Comment by mrmartineau** [comment]
ES2015 & ESLINT have been merged into [next branch](https://github.com/TryKickoff/kickoff/tree/next) now ([see commits](https://github.com/TryKickoff/kickoff/commits/next) :)

**Comment by ashleynolan** [comment]
:beers: :tada:

**Comment by nicbell** [comment]
Now I wont have to remove grunt icon every time.

**Comment by mrmartineau** [comment]
@nicbell that's interesting. Do you think Kickoff have an icon solution?

**Comment by mrmartineau** [comment]
Removal of old IE stuff has now been merged into [next](https://github.com/TryKickoff/kickoff/tree/next) [see commits](https://github.com/TryKickoff/kickoff/commit/5d66a4277cf03365106a9b30f7e6a2333b29e8e6)

**Comment by ashleynolan** [comment]
I’ve merged in the grid changes and have removed Grunticon – would be worth taking a look through and make sure I’ve caught all the references though.

That’s almost all the checklist done! 🚀

**Comment by mrmartineau** [comment]
I think the only thing left to do is to merge all changes into the yeoman generator.. and double-check everything else..

**Comment by ashleynolan** [comment]
Awesome 👍  I’m a bit pre-occupied this week as I’ve got a talk to finish by Friday, but reckon should be more than possible to test and release the new version by the end of next week?  Sound like a plan?

**Comment by nicbell** [comment]
Now that we are using Babel, we should consider, https://babeljs.io/#polyfill instead of shimly. 

Shimly does have the benefit of only shipping polyfills to old browsers. This could be solved by having more than one JS build with Babel. Two builds also means modern browsers could have different  presets using more native features rather than transpiled code. Thoughts?

**Comment by mrmartineau** [comment]
@nicbell yes, I agree. Can you see if it can be easily integrated into Kickoff?

**Comment by jpdriver** [comment]
@nicbell @mrmartineau not sure about browserify but integration looks super easy with webpack 😄 
```
With webpack.config.js, add babel-polyfill to your entry array:

module.exports = {
   entry: ['babel-polyfill', './app/js']
};
```

**Comment by ashleynolan** [comment]
We use [polyfill.io](https://cdn.polyfill.io/v2/docs/) for our polyfills now - relies on an 3rd party CDN but we have a fallback shim script in case it ever were to go down.  Has the benefit of only ever serving up what is needed for the particular browser the user is using, so for latest chrome it’s extremely lightweight.

**Comment by mrmartineau** [comment]
Polyfill.io looks amazing. Do we remove shimly in place of this?

**Comment by ashleynolan** [comment]
Yeh, the way we do it is to hit the CDN, test if the script is returned and if it doesn’t for whatever reason, we load in a local script with a bunch of polyfills (we just save down a minified polyfill.io script with the polyfills we need switched on [like this](https://cdn.polyfill.io/v2/polyfill.min.js?features=default,console,fetch,promise&flags=gated,always)).

It’s a really nice service though – and it’s used on some large-scale sites so the chances of it ever going down are pretty slim.

**Comment by mrmartineau** [comment]
@nicbell has already removed shimly. @ashleynolan would you be able to add your test and fallback to a gist?

**Comment by ashleynolan** [comment]
Yeh, we’re re-working this part at the moment (as the script we used was a bit cumbersome), but I’ll add it in once that’s done.

**Comment by ashleynolan** [comment]
Where are we on the v7 release?  Don’t think the fallback stuff needs to go in for release (can add that as a point release).  Are there any other changes that need to be made now?

**Comment by mrmartineau** [comment]
It needs testing by everyone again. Would @nicbell, @munkychop, @jpdriver, @tommaton and anyone else please test the next branch? See the [changelog](https://github.com/TryKickoff/kickoff/blob/next/changelog.md#700---21052016) for all the updates.

Also, Statix in the generator needs to be updated, no?

**Comment by ashleynolan** [comment]
Probably – I’ll check it out today and see what needs updating in there

**Comment by munkychop** [comment]
@mrmartineau I'm not able to use Kickoff much at the moment, but hoping to do so in the near future

**Comment by mrmartineau** [comment]
v7 pushed! 🎉
